openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: Documentación de la API para gestionar usuarios

servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /api/users:
    get:
      summary: Obtiene todos los usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '500':
          description: Error interno del servidor

  /api/users/{uid}:
    get:
      summary: Obtiene un usuario por ID
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
            example: "adssoaidjasd.1212dqsda"
          description: ID único del usuario
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualiza un usuario por ID
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
            example: "adssoaidjasd.1212dqsda"
          description: ID único del usuario
      requestBody:
        description: Datos a actualizar del usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateUser'
      responses:
        '200':
          description: Usuario actualizado correctamente
        '404':
          description: Usuario no encontrado
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor

    delete:
      summary: Elimina un usuario por ID
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
            example: "adssoaidjasd.1212dqsda"
          description: ID único del usuario
      responses:
        '200':
          description: Usuario eliminado correctamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: ID único del usuario
          example: "adssoaidjasd.1212dqsda"
        name:
          type: string
          description: Nombre del usuario
          example: "John Doe"
        email:
          type: string
          description: Correo electrónico del usuario
          example: "johndoe@example.com"
        role:
          type: string
          description: Rol del usuario en el sistema
          example: "admin"

    UserResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        payload:
          $ref: '#/components/schemas/User'

  requestBodies:
    UpdateUser:
      type: object
      properties:
        name:
          type: string
          description: Nombre del usuario
          example: "John Doe Updated"
        email:
          type: string
          description: Correo electrónico actualizado del usuario
          example: "johnupdated@example.com"
        role:
          type: string
          description: Nuevo rol del usuario
          example: "user"
